<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeManagement.Api\EmployeeManagement.Api.csproj" />
    <ProjectReference Include="..\EmployeeManagement.Data\EmployeeManagement.Data.csproj" />
  </ItemGroup>

</Project>
